<a href="https://colab.research.google.com/github/komarojugnanavi79-rgb/IIy-IIIs-python/blob/main/unit3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

array1= np.array([10, 20, 30])

array2= np.array([1, 2, 3])

result = np.add(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("Result (Array1 + Array2):", result)

Array 1: [10 20 30]
Array 2: [1 2 3]
Result (Array1 + Array2): [11 22 33]


In [2]:
# Program (b)
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Test if none of the elements is zero
result = np.all(arr)  # returns True if all elements are non-zero

print("Array:", arr)
print("None of the elements are zero:", result)

Array: [1 2 3 4 5]
None of the elements are zero: True


In [3]:
# Program (a)
import numpy as np

# Create a NumPy array
arr = np.array([10, 25, 30, 45, 50, 60, 70, 80, 90])

# Specify a number for comparison
num = 50

# Extract numbers less than and greater than 'num'
less_than = arr[arr < num]
greater_than = arr[arr > num]

print("Original array:", arr)
print("Numbers less than", num, ":", less_than)
print("Numbers greater than", num, ":", greater_than)

# Example of repr() to show string representation of an array
print("String representation using repr():", repr(arr))

Original array: [10 25 30 45 50 60 70 80 90]
Numbers less than 50 : [10 25 30 45]
Numbers greater than 50 : [60 70 80 90]
String representation using repr(): array([10, 25, 30, 45, 50, 60, 70, 80, 90])


In [4]:
# Program (b)
import numpy as np

# Create a 2D NumPy array
arr = np.array([
    [3, 7, 1],
    [10, 2, 9],
    [5, 6, 8]
])

print("Array:\n", arr)

# Find overall max and min
max_value = np.max(arr)
min_value = np.min(arr)

# Find indices of max and min
max_index = np.argmax(arr)
min_index = np.argmin(arr)

# Find indices along an axis (e.g., rows or columns)
max_indices_row = np.argmax(arr, axis=1)   # max in each row
min_indices_col = np.argmin(arr, axis=0)   # min in each column

print("\nMaximum value:", max_value)
print("Minimum value:", min_value)
print("Index of maximum value (flattened):", max_index)
print("Index of minimum value (flattened):", min_index)
print("Indices of max in each row:", max_indices_row)
print("Indices of min in each column:", min_indices_col)

Array:
 [[ 3  7  1]
 [10  2  9]
 [ 5  6  8]]

Maximum value: 10
Minimum value: 1
Index of maximum value (flattened): 3
Index of minimum value (flattened): 2
Indices of max in each row: [1 0 2]
Indices of min in each column: [0 1 0]
